#
# MIT License
#
# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
nameOverride: ""

global:
  chart:
    name: ""  # set at deploy time automatically, no need to ever set explicitly
    version: ""  # set at deploy time automatically, no need to ever set explicitly

trustDomain: shasta
vshasta: false

server:
  disableExternalCerts: true
  replicaCount: 3
  lb:
    local: "10.92.100.83"
    cluster: "10.92.100.84"
  port: 8081
  logLevel: INFO
  jwtIssuer: http://crayspire.local/shasta
  caTTL: 2160h
  svidDefaultTTL: 12h
  database: spire
  maxOpenDBConns: 20
  registrationPort: 54440
  priorityClassName: csm-high-priority-service
  tokenService:
    computeEntry: compute/tenant1
    computeClusterEntry: compute
    ncnEntry: ncn/tenant1
    ncnClusterEntry: ncn
    storageEntry: storage/tenant1
    storageClusterEntry: storage
    uanEntry: uan/tenant1
    uanClusterEntry: uan
    tokenTTL: 10800
    enableXNameWorkloads: false
  annotations: {}

  init:
    repository: artifactory.algol60.net/csm-docker/stable/sdlc-ops/wait-for-it
    tag: "1.0.0"
    pullPolicy: IfNotPresent

  init2:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/library/alpine
    tag: 3.16
    pullPolicy: IfNotPresent

  image:
    repository: artifactory.algol60.net/csm-docker/stable/gcr.io/spiffe-io/spire-server
    tag: 1.5.5
    pullPolicy: IfNotPresent

  registration:
    repository: artifactory.algol60.net/csm-docker/stable/spire-tokens
    tag: 3.1.0
    pullPolicy: IfNotPresent

  persistentVolume:
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    storageClass: ""

cray-postgresql:
  nameOverride: cray-spire
  sqlCluster:
    enabled: true
    instanceCount: 3
    postgresVersion: "11"
    volumeSize: 60Gi
    podPriorityClassName: csm-high-priority-service
    users:
      spire: []
    databases:
      spire: spire
    tls:
      issuer: cert-manager-issuer-common
    resources:
      limits:
        cpu: "8"
        memory: 8Gi
      requests:
        cpu: "4"
        memory: 4Gi
    waitForItJob: false
    connectionPooler:
      enabled: true
    parameters:
      idle_in_transaction_session_timeout: "5000"
      statement_timeout: "60000"
    backup:
      # Backups are disabled due to issues with client SVTs after restores.
      # It is better to completely reinstall the spire server and rejoin all
      # nodes than to restore from a backup.
      enableLogicalBackup: false

tls:
  issuer: cert-manager-issuer-common

agent:
  logLevel: INFO
  wlSocket: /run/cray-spire/sockets

  init:
    repository: artifactory.algol60.net/csm-docker/stable/sdlc-ops/wait-for-it
    tag: "1.0.0"
    pullPolicy: IfNotPresent

  init2:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/library/alpine
    tag: 3.16
    pullPolicy: IfNotPresent

  image:
    repository: artifactory.algol60.net/csm-docker/stable/gcr.io/spiffe-io/spire-agent
    tag: 1.5.5
    pullPolicy: IfNotPresent

jwks:
  domain: vshasta.io
  uriPrefix: spire-jwks
  logLevel: INFO
  port: 80
  replicaCount: 3
  priorityClassName: csm-high-priority-service

  image:
    repository: artifactory.algol60.net/csm-docker/stable/cray-spire-jwks
    tag: 0.4.0
    pullPolicy: IfNotPresent

  nginx:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/library/nginx
    tag: 1.18.0-alpine
    pullPolicy: IfNotPresent

bss:
  endpoint: http://cray-bss.services.svc.cluster.local/boot/v1/bootparameters
  curl:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/curlimages/curl
    tag: 7.80.0

ncn:
  url: https://cray-spire-tokens.spire:54440/api/token
  filename: join_token
  path: /var/lib/spire
  init:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/library/alpine
    tag: 3.16
  curl:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/curlimages/curl
    tag: 7.80.0
  pause:
    repository: artifactory.algol60.net/csm-docker/stable/k8s.gcr.io/pause
    tag: 3.4.1

kubectl:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker-kubectl
    tag: 1.19.15
    pullPolicy: IfNotPresent
