#
# MIT License
#
# (C) Copyright 2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-{{ include "spire.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "spire.name" . }}-server
  policyTypes:
    - Ingress
  ingress:
    - from:
      # BSS Access to request tokens for compute and UANs
      - namespaceSelector:
          matchLabels:
            name: services
        podSelector:
          matchLabels:
            app.kubernetes.io/name: cray-bss
      # request-ncn-join-token joins kubernetes NCNs via a daemonset
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
        podSelector:
          matchLabels:
            name: request-ncn-join-token
      # joining storage NCNs uses a spire-server pod to request tokens
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
        podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ include "spire.fullname" . }}-server
      # TPM-Provisioner need to request
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
        podSelector:
          matchLabels:
            app.kubernetes.io/name: tpm-provisioner
      ports:
        - protocol: TCP
          port: 54440
    # Allow access to spire server from anywhere.
    - from: []
      ports:
        - protocol: TCP
          port: 8081
