name: Kubescape scanning for misconfigurations
on: [push]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kubescape/github-action@main
      continue-on-error: true
      with:
        format: sarif
        outputFile: results
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
  kubelinter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Scan yaml files with kube-linter
      uses: stackrox/kube-linter-action@v1.0.4
      id: kube-linter-action-scan
      with:
        directory: charts/
        format: sarif
        output-file: kube-linter.sarif
      continue-on-error: true
    - name: Upload SARIF report files to GitHub
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: kube-linter.sarif
